# Generated by Django 4.1.7 on 2023-04-01 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0004_chapter_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.FileField(null=True, upload_to='media', verbose_name='Прикрепленный_файл'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='file',
            field=models.FileField(null=True, upload_to='media', verbose_name='Прикрепленный_файл'),
        ),
        migrations.AlterField(
            model_name='image',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='contentapp.article', verbose_name='Раздел'),
        ),
    ]
