# Generated by Django 4.1.7 on 2023-04-01 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0005_article_file_chapter_file_alter_image_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='contentapp.chapter', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='image',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='contentapp.article', verbose_name='Статья'),
        ),
    ]
