# Generated by Django 4.1.7 on 2023-04-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0008_alter_attachment_options_attachment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='description',
        ),
        migrations.AddField(
            model_name='chapter',
            name='text',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Описание'),
        ),
    ]
